name: mm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - pytorch-lightning
  - torchmetrics
  - torchio
  - monai
  - pip:
    - -r requirements.txt